name: Publish Package and Deploy Translations

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
      - 'scripts/**'
      - 'package.json'
      - '.github/workflows/publish.yml'

jobs:
  build-and-deploy:
    # Versiyonlama commit'lerinin sonsuz bir döngüye girmesini engeller
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # Versiyon artışı commit'lerini ve etiketleri push'lamak için
      pages: write # GitHub Pages'e dağıtım için
      packages: write # GitHub Packages'e yayınlamak için

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Versiyonlama için tam git geçmişini yükle
          fetch-depth: 0

      - name: Cache previous translations from gh-pages
        # gh-pages dalını dist-cache klasörüne klonla. Dal yoksa (ilk çalıştırma), hata vermeden devam et.
        run: |
          git clone --branch gh-pages --single-branch --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ./dist-cache || echo "No previous translations found, proceeding with a clean build."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Generate all translation files
        run: npm run translate:all
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # Betiğin okuyabilmesi için önbellek dizinini ortam değişkeni olarak ayarla
          TRANSLATION_CACHE_DIR: ./dist-cache

      - name: Deploy Translations to GitHub Pages (CDN)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Create Manifest File
        run: echo "{\"version\":\"${{ github.sha }}\"}" > ./dist/manifest.json

      - name: Configure Git for version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version if tag does not exist
        id: version_bumper
        run: |
          # Calculate the next version string (e.g., "v1.0.3") without creating a tag
          NEXT_VERSION=$(npm version patch --no-git-tag-version)

          # Check if the tag for the next version already exists
          if git rev-parse -q --verify "refs/tags/${NEXT_VERSION}"; then
            echo "Tag ${NEXT_VERSION} already exists. Skipping version bump and publish."
            echo "SKIPPED=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${NEXT_VERSION} does not exist. Proceeding with version bump."
            git add package.json
            git commit -m "chore(release): publish ${NEXT_VERSION}"
            git tag "${NEXT_VERSION}"
            echo "SKIPPED=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to GitHub Packages
        if: steps.version_bumper.outputs.SKIPPED == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes and tags to the repository
        if: steps.version_bumper.outputs.SKIPPED == 'false'
        run: git push && git push --tags
